### ISSUE TITLE
feat(Sponsors): Partner with other Discord communities

### ISSUE THREAD

**Issue by a-trost** [frontend-horse/holiday-show-page-2022#18]
## The goal

- Bring the communities together, all raising money for this great cause at the end of the year.
- Introduce members of each to other warm and welcoming communities they wouldn’t have heard about otherwise.

## The current plan

- Partner communities help to promote the event
- Someone from the partner community creates a 1m video that gets played during the intermission with the other community videos
- Community sponsorship is its own tier and get displayed on the website
- We ask the community leader(s) to donate $50 to the charity

## Questions

- What’s a good amount of money to make the donation?
- Is there a way to make **many to many** connections, rather than **one to many** (Frontend Horse would be the hub, but can we make it more of a circle/webring?)
    - What if each video ends by saying “And I’m pleased to announce the wonderful [next community in list] Discord”?

## Tasks
- [ ] Reach out to communities
- [ ] Collect information from participants
- [ ] Come up with criteria for video
- [ ] Provide them with promotional images/text/etc.
- [ ] Assist them with and collect their video
- [ ] @a-trost makes a video as an example.

**Comment by leifniem** [comment]
I think some of these are done by now
